import { Geist, Geist_Mono,Island_Moments } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const island = Island_Moments({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-island",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${island.variable}`}>
        {children}
      </body>
    </html>
  );
}
